spring:
  application:
    name: order
  rabbitmq:
    host: 192.168.3.102
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1230
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
env:
  dev2
